
const grid=document.querySelector('#projectsGrid');let projects=[];
const modal=document.querySelector('#galleryModal'),gallery=document.querySelector('#gallery');
fetch('projects.json').then(r=>r.json()).then(data=>{projects=data;render('all')});
function render(filter){grid.innerHTML='';projects.filter(p=>filter==='all'||p.service===filter).forEach(p=>{const card=document.createElement('article');card.className='project-card';card.innerHTML=`<img loading="lazy" src="assets/projects/${p.id}/thumb/${p.cover}" alt="${p.title}"><div class="project-overlay"><span>${p.service}</span><h3>${p.title}</h3><p>${p.location} • ${p.count} تصویر</p></div>`;card.onclick=()=>openGallery(p);grid.append(card)})}
document.querySelectorAll('.filter-bar button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-bar button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
function openGallery(p){document.querySelector('#modalTitle').textContent=p.title;document.querySelector('#modalService').textContent=p.service;document.querySelector('#modalSummary').textContent=p.summary;gallery.innerHTML='';for(let i=1;i<=p.count;i++){const n=String(i).padStart(2,'0');gallery.insertAdjacentHTML('beforeend',`<a href="assets/projects/${p.id}/full/${n}.jpg" target="_blank"><img loading="lazy" src="assets/projects/${p.id}/thumb/${n}.jpg" alt="${p.title} - تصویر ${i}"></a>`)}modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelector('.close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const menu=document.querySelector('.menu-btn'),nav=document.querySelector('nav');menu.onclick=()=>nav.classList.toggle('open');nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
